name: Deploy API na Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Configurar o Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 3. Compilar o projeto (Gerar o .jar)
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: 4. Enviar o .jar para o Servidor (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/portifolio-api-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/portfolio-deploy/"
          strip_components: 1

      - name: 5. Atualizar o Docker no Servidor (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/portfolio-deploy/

            printf 'FROM eclipse-temurin:21-jre-alpine\nWORKDIR /app\nCOPY portifolio-api-0.0.1-SNAPSHOT.jar app.jar\nEXPOSE 8080\nENTRYPOINT ["java", "-jar", "-Dapi.security.token.secret=portifolio-adriann", "app.jar"]\n' > Dockerfile

            sudo docker stop portfolio-api-server || true
            sudo docker rm portfolio-api-server || true
            sudo docker-compose up -d --build --force-recreate --no-deps portfolio-api
            sudo docker image prune -f